fix for missing html body
sdushantha/tmpmail pull request #16
Opened 2020-09-17 18:35 UTC by rjhbrunt

This is a fix for https://github.com/sdushantha/tmpmail/issues/14.

2020-09-17 19:10 UTC, sdushantha requested changes

2020-09-17 19:10 UTC, sdushantha commented on tmpmail
> +     fi
Couldn't you make that into a one-liner?
```bash
[ -z "$HTML_BODY" ] && HTML_BODY=$(jq -r ".textBody" <<<"$DATA")
```

2020-09-17 20:28 UTC, rjhbrunt commented on tmpmail
> +     fi
Yes 🙃 bash isn't my strong suit. I made the change

2020-09-18 04:28 UTC, sdushantha approved these changes

2020-09-18 04:29 UTC, sdushantha commented
Thank you for helping out! :)

2020-09-18 04:29 UTC, merged