Fix jq parse error by replacing echo with printf.
sdushantha/tmpmail pull request #30
Opened 2020-10-01 21:56 UTC by GReagle

I was getting "parse error: Invalid string: control characters from U+0000 through U+001F must be escaped" before I replaced echo with printf.  It is best practice to avoid echo anyway when dealing with arbitrary data.

2020-10-02 18:18 UTC, sdushantha requested changes

2020-10-02 18:18 UTC, sdushantha commented on tmpmail
> +    printf'
Two things here:
- Use `"` instead of `'` so that it is consitant throughout the script
- Add a space between `printf` and the quote

2020-10-02 18:20 UTC, sdushantha commented
> It is best practice to avoid echo anyway when dealing with arbitrary data.

I agree with you on this. If you make the changes that I have requested, then this PR should be ready to be merged

2020-10-02 18:58 UTC, GReagle commented on tmpmail
> +    printf'
I made those changes, but I am not a git expert, and I might have made a mess of the commits in this branch.

2020-10-02 20:12 UTC, rpdelaney commented on tmpmail
> +    printf'
Maybe I misunderstand the PR description, but why is the heredoc being removed?

2020-10-02 20:30 UTC, sdushantha commented on tmpmail
> +    printf'
> why is the heredoc being removed?

Good point. I misread the code and thought `cat` was `echo` and since @GReagle said "It is best practice to avoid echo anyway when dealing with arbitrary data", I thought it would be best to use `printf` instead.


@GReagle, could you revert it back to the heredoc? I for some strange reason thought that the `cat` command was an `echo` command and wanted to follow the best practice thinking that it was `echo` and not `cat`.

My apologies for the confusion I created

2020-10-02 22:25 UTC, GReagle commented on tmpmail
> +    printf'
The change from the cat with a heredoc to a printf is not directly relevant to the problem description.  I included it with this change set because it is an insertion of a printf, like the other changes in this set.

I changed it from a cat with a heredoc to a printf because:
1. less lines
2. no need for any comment
3. more conventional
4.

2020-10-02 22:29 UTC, GReagle commented on tmpmail
> +    printf'
As I wrote above, I think that I might have made a mess of the commits in this (git) branch.  So, I don't think I'll be putting any more work into this particular (git) branch.  I might make a new fresh git branch and re-do the changes.  If I do, I can leave the cat with a heredoc alone.

2020-10-03 00:31 UTC, rpdelaney commented on tmpmail
> +    printf'
Honestly, I'm not sure the comment is necessary with the heredoc either. I disagree that using `printf '` with a newline is more conventional than a heredoc, but I'm not sure how to quantify the conventionality of shell programming idioms...

2020-10-03 13:22 UTC, GReagle commented
Disregard this pull request please.  It has too many needless confusing commits.  I submitted a new pull request.

2020-10-03 16:04 UTC, closed without merging