Add feature to download attachments
sdushantha/tmpmail pull request #46
Opened 2020-12-24 09:13 UTC by mehtaarn000

This feature will allow users to download attachments from emails. Happy Holidays!

2021-01-07 08:24 UTC, sdushantha commented
I think a better implementation would be as follows:
- **For STDOUT**
Output the actual URLs to the files along with the email body. This way, the user can select the desired URL and download it either using command-line tool such as `curl` or `wget`, or they can open it in their web browser.

- **For browser mode**
At the very bottom of the email, show the file names which is a hyperlink to the download URL. This way, the user can click on it and download the file.
It would look something like this:
> **To:** jshdfsldjsa@1secmail.com
> **From:** example@example.com
> **Subject:** Hello World
>Hey Bob,
>
>I have attached the files needed for the project in this email.
>
>Thanks,
>Alice
>
> ---
>
> **Attachments**
> [document.pdf](example.com)
> [archive.zip](example.com)

2021-01-07 09:13 UTC, mehtaarn000 commented
Could the stdout look something like this:

> [Attachments in $ID]
>
> https://www.1secmail.com/api/v1/?action=download&login=demo&domain=1secmail.com&id=639&file=iometer.pdf
> https://www.1secmail.com/api/v1/?action=download&login=demo&domain=1secmail.com&id=639&file=textfile.txt

2021-01-07 10:38 UTC, mehtaarn000 commented
Just finished refactoring the code based on your implementation.

2021-01-07 10:42 UTC, sdushantha commented on tmpmail
> +            --attachments | -a) list_attachments "$2" && exit ;;
The listing of attachments should be done automatically.  Because not all emails state that there is an attachment, so it could easily be missed by the receiver.

2021-01-07 10:43 UTC, sdushantha commented on README.md
> +        Download an attachment from an email
This can be removed as it is not used

2021-01-07 10:44 UTC, sdushantha requested changes

2021-01-07 10:44 UTC, sdushantha commented on tmpmail
> +            --attachments | -a) list_attachments "$2" && exit ;;
The listing of attachments should be done automatically. Because not all emails state that there is an attachment, so it could easily be missed by the receiver.

2021-01-07 10:44 UTC, sdushantha commented on README.md
> +        Download an attachment from an email
This can be removed as it is not used

2021-01-07 17:07 UTC, mehtaarn000 commented on tmpmail
> +            --attachments | -a) list_attachments "$2" && exit ;;
What do you mean by "automatically"? When running `tmpmail`?

2021-01-07 17:45 UTC, sdushantha commented on tmpmail
> +            --attachments | -a) list_attachments "$2" && exit ;;
Yeah, when running `tmpmail`. 

I should have probably said, "by default" instead of "automatically".

2021-01-07 20:35 UTC, mehtaarn000 commented on tmpmail
> +            --attachments | -a) list_attachments "$2" && exit ;;
How does this look as stdout when checking inbox:
> [ Inbox for gvoe8ei0s7a@1secmail.com ]
> 
> 110976930   example@gmail.com   Subject goes here
>
> [ Attachments in 110976930 ]
>
> https://www.1secmail.com/api/v1/?action=download&login=demo&domain=1secmail.com&id=639&file=iometer.pdf

2021-01-08 12:49 UTC, sdushantha commented
I made a few changes to your code so that it is a little shorter.

For the attachment urls that get sent to stdout, they get shortened using [0x0.st](https://0x0.st). This is so that everything looks cleaner on the terminal. In my opinion, the url that we get from 1secmail.org is way too long to be nicely shown onto the terminal.

2021-01-08 13:14 UTC, sdushantha commented
I made a few changes to your code so that it is a little shorter.

For the attachment urls that get sent to stdout, they get shortened using [is.gd](https://is.gd/). This is so that everything looks cleaner on the terminal. In my opinion, the url that we get from 1secmail.org is way too long to be nicely shown onto the terminal.

2021-01-08 13:16 UTC, sdushantha approved these changes

2021-01-08 13:16 UTC, merged