Get list of available domains direct from API instead of hardcoded list
sdushantha/tmpmail pull request #73
Opened 2022-04-28 09:02 UTC by aincube

This fix implements 2 functions:
 - *get_list_of_domains* which receives list of available domains direct from API
 - *show_list_of_domains* which shows list of domains in case of *-d* option

2022-04-28 09:12 UTC, sdushantha requested changes

2022-04-28 09:12 UTC, sdushantha commented on tmpmail
> +    domains=$(printf "${data//[\"\[\]]/}" | tr "," " ")
I think it would be better if this function just printed the output and so that we can later on save the output to a variable instead of doing it in the function itself.
So we can do something like this:
```bash
domains=$(get_list_of_domains)
````

This will make it easier for others when they read through the code. Let me know what your thoughts are on this :+1:

2022-04-28 09:31 UTC, aincube commented on tmpmail
> +    domains=$(printf "${data//[\"\[\]]/}" | tr "," " ")
Bingo! Of course it's much better this way. I'm not so familiar with shell-scripts, but now I understand them much better - thanks to you )

2022-04-29 07:31 UTC, sdushantha commented
![image](https://user-images.githubusercontent.com/27065646/165901962-18cd8d13-b1b5-4d74-8dd5-16bcdbcb9b34.png)

There is an issue with the regex though. You could actually create the regex based on the list of domains.

2022-04-29 08:04 UTC, aincube commented
My fault, I just search for word domain, but passed that regex rule also use domains list. Seems now it's working
![image](https://user-images.githubusercontent.com/365061/165906601-5c93bd8b-8e99-484e-bf09-771b00ff0357.png)

> ![image](https://user-images.githubusercontent.com/27065646/165901962-18cd8d13-b1b5-4d74-8dd5-16bcdbcb9b34.png)
> 
> There is an issue with the regex though. You could actually create the regex based on the list of domains.

2022-04-29 08:09 UTC, sdushantha commented
There are few issues reported from `shellcheck` and thats because the you've added non-POSIX compliant code. If you fix that up, I think this PR shold be ready to merge :+1:

2022-04-29 09:27 UTC, aincube commented
Whoa ) I switched all *string replacements* to *tr* and it looks like it passes shellchecker now.
![image](https://user-images.githubusercontent.com/365061/165918573-18e7e6b2-e1ba-4a8e-b57a-ed082fb3f488.png)

2022-05-04 19:49 UTC, sdushantha commented
I made a few small changes, do you agree with them?

2022-05-04 21:57 UTC, aincube commented
> I made a few small changes, do you agree with them?

Yes, perfect, thanks!

2022-05-05 05:54 UTC, sdushantha approved these changes

2022-05-05 05:54 UTC, merged